source "https://rubygems.org"

ruby "3.3.4"

gem "github-pages", "~> 232", group: :jekyll_plugins

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.17.0"
end

install_if -> { RUBY_PLATFORM =~ %r!mingw|mswin|java! } do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1.0", install_if: Gem.win_platform?

gem "kramdown-parser-gfm"

gem "webrick", "~> 1.8"
